# -*- coding: utf-8 -*-
"""python med

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XdpyXgBpaIVuyAZ6rGSb6kdhnme_eFDU
"""

22 / 7

22 // 7

22 % 7

# assignment operator
a = 5 #assign value to a
print (a)
x = [10,20,30]
x[0] = 1
print(x[0])
# we cannot change the value of list without including the list

#relational operators in python
3 == 3 #test for equality with ==
3!= 3  #test for intequality with !=
3 > 1  # test greater then with >
3 >= 3 #test greater than or equal to with >=
3 < 4  #test lesser then with <
3 <= 4 #test lesser then or equal to with <=

# Logical operators
not(2 == 2) # Using logical NOT
(1 != 1) and (1 < 1) #using logical AND
(1 >= 1) or (1 < 1) #using logical OR

(1 >= 1) or (1 < 1) #using logical OR

"""Python inbuilt Datastructures
1.LIST
2.TUPLE
3.DICTIONARY
4.SET

LIST: It is ordered,mutable collection that can store items or different data types.they are defined using square brackets[].

TUPLE: orderedimmutable collection, meaning their contents cannot be changed after creation.they are defined using parameters().

SETS:Unordered collection of unique elements. they do not allow duplicate values and are defined using curly braces{} or the set() constructor.
"""

my_Set = {1,2,3,2} #it do not allow the duplicate values
my_Set

"""DICTIONARIES: Unordered collections of key-value paries, where each key must be unique. they are defined using curly braces{} with key-vale pairs separated by colons.

"""

my_dict = {"name": "Aneesh", "age": 18}
my_dict

"""**Datastructure**:different ways of storing and accessing and manuplating the data in main memory of a computer."""

my_list = ['a','e','i','o','u']
my_list.index('a')

"""#List operations"""

mylist=['a','e','i','o','u']
mylist.index('a')

mylist=[1,2,3,4,4,5]
mylist.count(4)

mylist.append(6)
mylist

mylist.remove(6)
mylist

del(mylist[0:1])
mylist

mylist

mylist.reverse()
mylist

# extend is same as append (adding elements at the last of list) but it can extend a
#list with another list
mycars =["Ford","BMW"]
mylist.extend(mycars)
mylist
#differnes b/w append() and extend()
#append can add only a single elements at the end of the list

mylist.pop(-1) #negative index accesses elements from last of list
mylist
# postive index accesses elements from start or first of list

mylist.insert(0,'M') # insert an element
mylist

"""#STRINGS"""

mystring ="welcome to python"
mystring

mystring[3]

"""#List processing in python

Return a list were each element is a running sum.
sample input:[10,20,5,1]
sample output:[10,30,35,36]

#STEPS:-
1. create a empty result list.
2. keep a total variable starting at 0.
3. loopnthrough each number.
4. add to total,append total to result.
"""

def runningSum(nums):
  result=[]
  total=0
  for n in nums: #loop started
    total+= n    # add the value to total
    result.append(total) # append the sum to the result list
  return(result)
print(runningSum([10,20,30,2,-1]))

"""#sum of elements in a list"""

def a(nums):
  total=0
  for n in nums: #loop started
    total+= n    # add the value to total
  return(total)
print(a([10,20,30,2,-1]))

"""#count no.of even numbers in a list"""

def even(nums):
 count = 0
 for n in nums:
   if n%2 == 0:
      count += 1
 return count
print(even([10,2,3,5,7,9]))

"""#Reverse a list"""

def reverselist(nums):
  return nums[::-1]
print(reverselist([2,4,6,8,10]))

#slicing the list
mylist = [1,2,3,4,5,6,8]
#the list slices from the beginning to end, taking every second element
print(mylist[::2])
print(mylist[::3])
print(mylist[::-1])
print(mylist[::-2])
print(mylist[::-3])

"""::(double colons) in pyton enables flexible extraction and manipulation of sequence elements

#Maximum number in a list
"""

def max(nums):
 max =nums[0] #assign first of list as maximum
 for n in nums:
   if n > max:
    max = n
 return max

print(max([10,2,3,5,7,9]))

"""#minimun of a list"""

def min(nums):
 min =nums[0] #assign first of list as maximum
 for n in nums:
   if n < min:
    min = n
 return min

print(min([10,2,3,5,7,9]))

"""#merge two sorted list"""

def merge(list1,list2):
    return sorted(list1+list2)
print(merge([1,2,3,4],[5,6,7,8]))

"""#square of a sorted list"""

def square(nums):
  return sorted(x**2 for x in nums)
print(square([1,2,3,4,5]))

def deposit(accounts):
  return max(sum (cust)for cust in accounts)
print(deposit([[100,52],[3,60]]))

"""#Find two indices"""

def twosum(nums,target):
  seen={}
  for i, n in enumerate(nums):
    diff = target - n
    if diff in seen:
      return [seen[diff],+i]
    seen[n] = i
    print(seen)
print(twosum([2,0,11,15],26))

"""#Experiment 4
Objective : To design a menu driven application for grocery store checkout system using list data structure in python.

"""

# Grocery Store Checkout
# Available products
products = {
    "Apples": 50,
    "Bananas": 30,
    "Milk": 60,
    "Bread": 40,
    "Eggs": 70
}

# Empty cart
cart = {}

print("\n===== Grocery Store Menu =====")
print("1. Show available products and prices")
print("2. Empty cart")
print("3. Display menu")
print("4. Add item to cart")
print("5. Remove item from cart")
print("6. Show cart")
print("7. Exit")

while True:
    choice = input("\nEnter your choice (1-7): ")

    if choice == "1":
        print("\n--- Available Products ---")
        for item in products:
            print(item, ":", products[item])

    elif choice == "2":
        cart.clear()
        print("\nCart is now empty!")

    elif choice == "3":
        print("\n===== Grocery Store Menu =====")
        print("1. Show available products and prices")
        print("2. Empty cart")
        print("3. Display menu")
        print("4. Add item to cart")
        print("5. Remove item from cart")
        print("6. Show cart")
        print("7. Exit")

    elif choice == "4":
        print("\n--- Available Products ---")
        for item in products:
            print(item, ":", products[item])
        item = input("Enter product name to add: ")
        if item in products:
            qty = int(input("Enter quantity: "))
            if item in cart:
                cart[item] = cart[item] + qty
            else:
                cart[item] = qty
            print(qty, item, "added to cart.")
        else:
            print("Item not available.")

    elif choice == "5":
        if cart == {}:
            print("\nCart is empty. Nothing to remove.")
        else:
            print("Your Cart:", cart)
            item = input("Enter product name to remove: ")
            if item in cart:
                qty = int(input("Enter quantity to remove: "))
                if qty >= cart[item]:
                    del cart[item]
                    print(item, "removed from cart.")
                else:
                    cart[item] = cart[item] - qty
                    print(qty, item, "removed from cart.")
            else:
                print("Item not in cart.")

    elif choice == "6":
        if cart == {}:
            print("\nYour cart is empty.")
        else:
            print("\n--- Your Cart ---")
            total = 0
            for item in cart:
                qty = cart[item]
                price = products[item] * qty
                total = total + price
                print(item, "x", qty, "=", price)
            print("Total Bill:", total)

    elif choice == "7":
        print("Thank you for shopping! Goodbye.")
        break

    else:
        print("Invalid choice, try again.")